// RiptideExtension.idl : IDL source for RiptideExtension
//

// This file will be processed by the MIDL tool to
// produce the type library (RiptideExtension.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(E7B6D1C2-56C9-4BF6-88E9-290D7D8AFFDC),
	helpstring("IRiptideHandler4 Interface"),
	pointer_default(unique)
]
interface IRiptideHandler4 : IUnknown{
};

[
	object,
	uuid(D3CCDB1D-BA81-4174-B0B7-2A13C60D634D),
	helpstring("IRiptideHandler2 Interface"),
	pointer_default(unique)
]
interface IRiptideHandler2 : IUnknown{
};

[
	object,
	uuid(966D16D2-6BF7-46C7-828D-7BFD42DAAA63),
	helpstring("IGoDriveContextMenuImpl Interface"),
	pointer_default(unique)
]
interface IGoDriveContextMenuImpl : IUnknown{
};
[
	uuid(006E7D34-3BA6-45CB-AA52-42DD992762F2),
	version(1.0),
	helpstring("RiptideExtension 1.0 Type Library")
]
library RiptideExtensionLib
{
	importlib("stdole2.tlb");
	[
		uuid(2AD819EF-3302-4570-B7E5-BAA927ADE61D),
		helpstring("RiptideHandler4 Class")
	]
	coclass RiptideHandler4
	{
		[default] interface IRiptideHandler4;
	};

	[
		uuid(34878F00-1827-4A4B-B4C2-9628D9E39EDE),
		helpstring("RiptideHandler2 Class")
	]
	coclass RiptideHandler2
	{
		[default] interface IRiptideHandler2;
	};

	[
		uuid(AEC95F8C-E0E8-4EF9-89E3-F26D21EBEC14),
		helpstring("RiptideContextMenuImpl Class")
	]
	coclass RiptideContextMenuImpl
	{
		[default] interface IGoDriveContextMenuImpl;
	};
};
